requires 'Data::ICal', '== 0.24';
requires 'JSON', '== 4.05';
requires 'LWP::Simple', '== 6.61';
requires 'LWP::Protocol::https', '== 6.10';
requires 'Geo::Coder::OSM', '== 0.03';
requires 'GIS::Distance', '== 0.19';
requires 'Date::ICal', '== 2.678';
requires 'Number::Format', '== 1.75';
requires 'String::Pad', '== 0.021';
