run-name: Build IJF calendar 🚀
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  Build-planetjudo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82149/actions-setup-perl@v1
        with:
          perl-version: '6.34'
      - run: cpanm --notest --installdeps .
      - run: perl ijf_ical.pl > ijf.ics
      - uses: stefanzweifel/git-auto-commit-action@v5