run-name: Build IJF calendar 🚀
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  Build-ijf-ical:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1.25.0
        with:
          perl-version: '5.34'
      - run: cpanm --notest --installdeps .
      - run: perl ijf_ical.pl > ijf.ics
      - uses: stefanzweifel/git-auto-commit-action@v5